---
abstract: 'Declarative 0MQ Infrastructure'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZMQ-Declare
requires:
  Carp: 0
  Clone: 0
  Data::Dumper: 0
  Data::Rx: 0
  File::Spec: 0
  JSON: 0
  Moose: 0
  Scalar::Util: 0
  Storable: 0
  Test::More: 0.88
  ZeroMQ: 0
  autodie: 0
  lib: 0
  parent: 0
resources:
  repository: http://github.com/tsee/ZMQ-Declare.git
version: 0.03
